In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier

X, y = make_classification(
    n_features=10, 
    n_samples=1000, 
    n_informative=8,
    n_redundant=2,
    n_repeated=0,
    n_classes=2, 
    random_state=42
)

In [7]:
from sklearn.model_selection import GridSearchCV

clf=GridSearchCV(
    DecisionTreeClassifier(),
    {
            'criterion':['ginni','entropy'],
            'max_depth':[5,10,15]
    },
    cv=5,
    return_train_score=False
)
clf.fit(X,y)

C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
15 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeClassifier must be a str among {'log_loss', 'entropy', 'gini'}. Got 'ginni' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [  nan   nan   nan 0.782 0.794 0.805]
  warnings.warn(

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'criterion': ['ginni', 'entropy'],
                         'max_depth': [5, 10, 15]})

In [8]:
clf.cv_results_

{'mean_fit_time': array([0.00020013, 0.00062442, 0.00088296, 0.01755629, 0.02122455,
        0.02286768]),
 'std_fit_time': array([0.00040026, 0.00051141, 0.00045144, 0.00400975, 0.00091132,
        0.00137364]),
 'mean_score_time': array([0.        , 0.        , 0.        , 0.00223517, 0.00124683,
        0.00109959]),
 'std_score_time': array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.12375224e-03,
        3.90853201e-04, 6.06230517e-05]),
 'param_criterion': masked_array(data=['ginni', 'ginni', 'ginni', 'entropy', 'entropy',
                    'entropy'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_max_depth': masked_array(data=[5, 10, 15, 5, 10, 15],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'params': [{'criterion': 'ginni', 'max_depth': 5},
  {'criterion': 'ginni', 'max_depth': 10},
  {'criterion': 'ginni', 'max_depth': 15},
  {'criterion': 'entropy', 'max_depth': 5},
  {'criterion': 'entropy', 'max_depth': 10},
  {'criterion': 'entropy', 'max_depth': 15}],
 'split0_test_score': array([  nan,   nan,   nan, 0.765, 0.78 , 0.765]),
 'split1_test_score': array([  nan,   nan,   nan, 0.785, 0.805, 0.775]),
 'split2_test_score': array([  nan,   nan,   nan, 0.765, 0.82 , 0.835]),
 'split3_test_score': array([  nan,   nan,   nan, 0.815, 0.775, 0.795]),
 'split4_test_score': array([  nan,   nan,   nan, 0.78 , 0.79 , 0.855]),
 'mean_test_score': array([  nan,   nan,   nan, 0.782, 0.794, 0.805]),
 'std_test_score': array([       nan,        nan,        nan, 0.0183303 , 0.01655295,
        0.03464102]),
 'rank_test_score': array([4, 4, 4, 3, 2, 1], dtype=int32)}

In [9]:
df=pd.DataFrame(clf.cv_results_)

In [10]:
df.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_depth,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000200,0.000400,0.000000,0.000000,ginni,5,"{'criterion': 'ginni', 'max_depth': 5}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
1,0.000624,0.000511,0.000000,0.000000,ginni,10,"{'criterion': 'ginni', 'max_depth': 10}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
2,0.000883,0.000451,0.000000,0.000000,ginni,15,"{'criterion': 'ginni', 'max_depth': 15}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
3,0.017556,0.004010,0.002235,0.001124,entropy,5,"{'criterion': 'entropy', 'max_depth': 5}",0.765,0.785,0.765,0.815,0.78,0.782,0.018330,3
4,0.021225,0.000911,0.001247,0.000391,entropy,10,"{'criterion': 'entropy', 'max_depth': 10}",0.780,0.805,0.820,0.775,0.79,0.794,0.016553,2

In [13]:
clf.best_params_

{'criterion': 'entropy', 'max_depth': 15}

In [14]:
from sklearn import svm

In [21]:
model_params={
    'decision_tree':{
        'model':DecisionTreeClassifier(),
        'params':{
            'criterion':['gini','entropy'],
            'max_depth':[5,10,15]
        }
    
    },

    'svm':{
        'model':svm.SVC(gamma='auto'),
        'params':{
            'C':[1,10,20],
            'kernel':['rbf','linear']
        }
    }
}

In [26]:
scores = []
for key,val in model_params.items():
    clf=GridSearchCV(
        val['model'],val['params'],
        cv=5,
        return_train_score=False
    )
    clf.fit(X,y)
    scores.append({
        'model':key,
        'best_score':clf.best_score_,
        'best_params':clf.best_params_
    })

scores

C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
15 fits failed out of a total of 30.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeClassifier must be a str among {'log_loss', 'entropy', 'gini'}. Got 'ginni' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [  nan   nan   nan 0.78  0.787 0.82 ]
  warnings.warn(

[{'model': 'decision_tree',
  'best_score': np.float64(0.8200000000000001),
  'best_params': {'criterion': 'entropy', 'max_depth': 15}},
 {'model': 'svm',
  'best_score': np.float64(0.9260000000000002),
  'best_params': {'C': 1, 'kernel': 'rbf'}}]

In [28]:
pd.DataFrame(scores)

           model  best_score                                best_params
0  decision_tree       0.820  {'criterion': 'entropy', 'max_depth': 15}
1            svm       0.926                  {'C': 1, 'kernel': 'rbf'}

In [32]:
from sklearn.model_selection import RandomizedSearchCV

clf=RandomizedSearchCV(
    DecisionTreeClassifier(),
    {
            'criterion':['ginni','entropy'],
            'max_depth':[5,10,15]
    },
    cv=5,
    return_train_score=False,
    n_iter=3
)
clf.fit(X,y)

C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
10 fits failed out of a total of 15.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py", line 1358, in wrapper
    estimator._validate_params()
  File "C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py", line 471, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeClassifier must be a str among {'log_loss', 'entropy', 'gini'}. Got 'ginni' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\rushi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [  nan   nan 0.789]
  warnings.warn(

RandomizedSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_iter=3,
                   param_distributions={'criterion': ['ginni', 'entropy'],
                                        'max_depth': [5, 10, 15]})

In [33]:
df=pd.DataFrame(clf.cv_results_)

In [35]:
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_criterion,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000215,0.000430,0.00000,0.000000,15,ginni,"{'max_depth': 15, 'criterion': 'ginni'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
1,0.000245,0.000490,0.00000,0.000000,10,ginni,"{'max_depth': 10, 'criterion': 'ginni'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,0.009705,0.000329,0.00044,0.000542,10,entropy,"{'max_depth': 10, 'criterion': 'entropy'}",0.77,0.8,0.82,0.76,0.795,0.789,0.021541,1